[package]
name = "ceres"
version = "0.1.0"
license = "MIT"
edition = "2021"
description = "A Gameboy/Color emulator"

[dependencies]
ceres_core = { path = "../ceres_core" }
clap = { version = "*", default-features = false, features = ["std", "help"] }
parking_lot = { version = "*", default-features = false }
anyhow = { version = "*", default-features = false, features = ["std"] }
sdl2 = { version = "*", features = ["unsafe_textures"] }
