[package]
name = "ceres-test-runner"
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
anyhow = "1.0"
ceres-core = { path = "../ceres-core" }
ceres-std = { path = "../ceres-std" }
clap = { version = "*", features = ["derive"] }
image = { version = "*", default-features = false, features = ["png"] }

[build-dependencies]
anyhow = "1.0"

[lints.clippy]
doc-markdown = { level = "allow", priority = 1 }
ignore_without_reason = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
nursery = "warn"
pedantic = "warn"
