[package]
name = "ceres-audio"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies.ceres-core]
path = "../ceres-core"

[dependencies.cpal]
version = "*"
default-features = false

[dependencies.ringbuf]
version = "*"

[dependencies.rubato]
version = "*"
