[workspace]
members = ["ceres_core", "ceres_front"]
default-members = ["ceres_front"]
resolver = "2"

[profile.dev]
opt-level = 2

[profile.test]
opt-level = 3
debug = 0

[profile.release]
opt-level = 3
strip = true
lto = true
debug = 0
panic = "abort"
