[workspace]
members = ["ceres_core", "ceres_sdl"]
default-members = ["ceres_sdl"]

[profile.dev]
opt-level = 2
strip = false
lto = false
debug = true

[profile.test]
opt-level = 3
debug = 0

[profile.release]
opt-level = "s"
strip = true
lto = true
debug = 0
panic = "abort"
