[workspace]
members = ["ceres_core", "ceres_sdl", "tests/blargg_runner"]
default-members = ["ceres_sdl"]

[profile.dev]
opt-level = 2
debug = 0

[profile.test]
opt-level = 3
debug = 0

[profile.release]
opt-level = 3
strip = true
lto = true
debug = 0
