enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
wrap_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "One"
condense_wildcard_suffixes = true
hex_literal_case = "Upper"
normalize_comments = true
reorder_impl_items = true
version = "Two"
format_strings = true
unstable_features = true
tab_spaces = 2
max_width = 79
fn_single_line = true
blank_lines_lower_bound = 0
use_small_heuristics = "Max"
