[package]
name = "ceres_glutin"
version = "0.1.0"
license = "MIT"
edition = "2021"
description = "A Gameboy/Color emulator"

[dependencies]
ceres_core = { path = "../ceres_core" }
glow = "*"
clap = { version = "*", features = ["derive"] }
sdl2 = "*"
