[package]
name = "ceres-egui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies.ceres-std]
path = "../ceres-std"

[dependencies.ceres-wgpu]
path = "../ceres-wgpu"

[dependencies.clap]
version = "*"
default-features = false
features = ["std", "derive"]

[dependencies.anyhow]
version = "*"

[dependencies.directories]
version = "*"

[dependencies.eframe]
version = "*"
default-features = false
features = ["default_fonts", "wgpu", "wayland", "accesskit"]

[dependencies.winit]
version = "*"

[dependencies.rfd]
version = "*"
