[package]
name = "rs_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "s"

[dependencies]
wasm-bindgen = "*"
ceres_core = { path = "../../ceres_core" }
either = "*"
